name: Deploy WebAssembly to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'cmd/wasm/**'
      - 'pkg/**'
      - '.github/workflows/deploy-web.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build WebAssembly
      run: |
        GOOS=js GOARCH=wasm go build -o web/static/imagekit.wasm cmd/wasm/main.go
        ls -lh web/static/imagekit.wasm
    
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: pyhub-imagekit
        directory: web
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}